const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Json,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.ScriptsInEvents.Y8api_Event1_Act1,
		C3.ScriptsInEvents.Y8api_Event2_Act1,
		C3.ScriptsInEvents.Y8api_Event3_Act1,
		C3.ScriptsInEvents.Y8api_Event4_Act1,
		C3.ScriptsInEvents.Y8api_Event5_Act1,
		C3.ScriptsInEvents.Y8api_Event6_Act1,
		C3.ScriptsInEvents.Y8api_Event7_Act1,
		C3.ScriptsInEvents.Y8api_Event8_Act1,
		C3.ScriptsInEvents.Y8api_Event9_Act1,
		C3.ScriptsInEvents.Y8api_Event10_Act1,
		C3.ScriptsInEvents.Y8api_Event11_Act1,
		C3.ScriptsInEvents.Y8api_Event12_Act1,
		C3.ScriptsInEvents.Y8api_Event13_Act1,
		C3.ScriptsInEvents.Y8api_Event14_Act1,
		C3.ScriptsInEvents.Y8api_Event15_Act1,
		C3.ScriptsInEvents.Y8api_Event16_Act1,
		C3.ScriptsInEvents.Y8api_Event17_Act1,
		C3.ScriptsInEvents.Y8api_Event18_Act1,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.ScriptsInEvents.Y8api_Event19_Act2,
		C3.ScriptsInEvents.Y8api_Event20_Act1,
		C3.ScriptsInEvents.Y8api_Event21_Act1,
		C3.ScriptsInEvents.Y8api_Event22_Act2,
		C3.ScriptsInEvents.Y8api_Event23_Act2,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Browser.Exps.Domain,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.ScriptsInEvents.Y8api_Event40_Act1,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{Audio: 0},
	{JSON_Config: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Array_Random: 0},
	{Array_Shufte: 0},
	{Array_Types: 0},
	{Array_TypesRandom: 0},
	{BG: 0},
	{active: 0},
	{is_skip: 0},
	{is_skip_next: 0},
	{x_start: 0},
	{y_start: 0},
	{dir: 0},
	{time_delay: 0},
	{is_animate: 0},
	{index_guide: 0},
	{block: 0},
	{block_skin: 0},
	{is_allow_skip: 0},
	{block_check: 0},
	{block_check_hozirital: 0},
	{test: 0},
	{btn_shufte: 0},
	{fx: 0},
	{LeavesCorner: 0},
	{titlegame: 0},
	{Tween: 0},
	{home_btn_play: 0},
	{btn_sound: 0},
	{box_decoration: 0},
	{setting_btn: 0},
	{watcher: 0},
	{ic_flash: 0},
	{level_txt: 0},
	{timer_txt: 0},
	{bg_controller: 0},
	{complete_controller: 0},
	{rope: 0},
	{title_controller: 0},
	{complete_btn_next: 0},
	{btn_home: 0},
	{fail_controller: 0},
	{fail_btn_replay: 0},
	{setting_controller: 0},
	{setting_btn_continue: 0},
	{box_notice: 0},
	{box_notice_txt: 0},
	{home_decoration: 0},
	{banner_notice: 0},
	{btn_home2: 0},
	{pointer: 0},
	{clear_btn: 0},
	{clear_controllers: 0},
	{clear_txt: 0},
	{clear_btn_yesNo: 0},
	{Text: 0},
	{mode: 0},
	{type: 0},
	{Pin: 0},
	{Timer: 0},
	{loadingFont: 0},
	{y8Logo: 0},
	{OnlineSave: 0},
	{localSave: 0},
	{onlineBtn: 0},
	{localSaveBtn: 0},
	{WelcomeFont: 0},
	{Sprite: 0},
	{Type: 0},
	{left: 0},
	{BlacklistFont: 0},
	{BlacklistFont2: 0},
	{Browser: 0},
	{saveArray: 0},
	{Mouse: 0},
	{clearBtnArray: 0},
	{FamilyBlockSkins: 0},
	{MoveTo: 0},
	{FamilyBlocks: 0},
	{FamilyBlockCheck: 0},
	{block_isTouch: 0},
	{block_uidSelectedFirst: 0},
	{block_stateCheck: 0},
	{block_isCheckValid: 0},
	{block_returnResultCheck: 0},
	{block_isMarkChecked: 0},
	{block_isStart: 0},
	{total: 0},
	{type1: 0},
	{type2: 0},
	{uid_selected: 0},
	{is_valid: 0},
	{direction_move: 0},
	{x1: 0},
	{y1: 0},
	{x2: 0},
	{y2: 0},
	{return_value: 0},
	{is_ok: 0},
	{uid: 0},
	{is_found: 0},
	{uid2: 0},
	{is_game_fail: 0},
	{index: 0},
	{uid1: 0},
	{i: 0},
	{total_block: 0},
	{count_pair: 0},
	{is_complete: 0},
	{index_random: 0},
	{layer_name: 0},
	{UI_stateLocked: 0},
	{state_fail: 0},
	{loaderCompleted: 0},
	{timer_isStart: 0},
	{timer: 0},
	{guide_isStarted: 0},
	{guide_index: 0},
	{key_main: 0},
	{loaderNextVar: 0},
	{gameName: 0},
	{SponsoredSite: 0},
	{blacklistSite: 0},
	{isLocal: 0},
	{isOnline: 0},
	{isLogin: 0},
	{isY8menu: 0},
	{userNameY8: 0},
	{saveKey: 0},
	{isDataLoaded: 0},
	{isPausedGameY8: 0},
	{isRewardGained: 0},
	{isRewardDismissed: 0},
	{isFrequencyCapped: 0},
	{isScreenSubmitted: 0},
	{isScoreSubmitted: 0},
	{g_prelogo: 0},
	{g_menulogo: 0},
	{destLogo: 0},
	{score_: 0},
	{name_: 0},
	{key_: 0},
	{saveKey_: 0},
	{saveItem_: 0},
	{loadkey_: 0},
	{image_: 0},
	{soundPausedGame: 0},
	{dataCheck: 0},
	{y8DadamissVar: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Array_Random: class extends self.IArrayInstance {},
	Array_Shufte: class extends self.IArrayInstance {},
	Array_Types: class extends self.IArrayInstance {},
	Array_TypesRandom: class extends self.IArrayInstance {},
	BG: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	block_skin: class extends self.ISpriteInstance {},
	block_check: class extends self.ISpriteInstance {},
	block_check_hozirital: class extends self.ISpriteInstance {},
	test: class extends self.ITextInstance {},
	btn_shufte: class extends self.ISpriteInstance {},
	fx: class extends self.ISpriteInstance {},
	LeavesCorner: class extends self.ISpriteInstance {},
	titlegame: class extends self.ISpriteInstance {},
	home_btn_play: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	box_decoration: class extends self.ISpriteInstance {},
	setting_btn: class extends self.ISpriteInstance {},
	watcher: class extends self.ISpriteInstance {},
	ic_flash: class extends self.ISpriteInstance {},
	level_txt: class extends self.ISpriteFontInstance {},
	timer_txt: class extends self.ISpriteFontInstance {},
	bg_controller: class extends self.ISpriteInstance {},
	complete_controller: class extends self.ISpriteInstance {},
	rope: class extends self.ISpriteInstance {},
	title_controller: class extends self.ISpriteInstance {},
	complete_btn_next: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	fail_controller: class extends self.ISpriteInstance {},
	fail_btn_replay: class extends self.ISpriteInstance {},
	setting_controller: class extends self.ISpriteInstance {},
	setting_btn_continue: class extends self.ISpriteInstance {},
	box_notice: class extends self.ISpriteInstance {},
	box_notice_txt: class extends self.ISpriteFontInstance {},
	home_decoration: class extends self.ISpriteInstance {},
	banner_notice: class extends self.ISpriteInstance {},
	btn_home2: class extends self.ISpriteInstance {},
	pointer: class extends self.ISpriteInstance {},
	clear_btn: class extends self.ISpriteInstance {},
	clear_controllers: class extends self.ISpriteInstance {},
	clear_txt: class extends self.ISpriteFontInstance {},
	clear_btn_yesNo: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	loadingFont: class extends self.ISpriteFontInstance {},
	y8Logo: class extends self.ISpriteInstance {},
	OnlineSave: class extends self.ISpriteInstance {},
	localSave: class extends self.ISpriteInstance {},
	onlineBtn: class extends self.ISpriteInstance {},
	localSaveBtn: class extends self.ISpriteInstance {},
	WelcomeFont: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BlacklistFont: class extends self.ISpriteFontInstance {},
	BlacklistFont2: class extends self.ISpriteFontInstance {},
	Browser: class extends self.IInstance {},
	saveArray: class extends self.IArrayInstance {},
	Mouse: class extends self.IInstance {},
	clearBtnArray: class extends self.IArrayInstance {},
	FamilyBlockSkins: class extends self.ISpriteInstance {},
	FamilyBlocks: class extends self.ISpriteInstance {},
	FamilyBlockCheck: class extends self.ISpriteInstance {}
}